name: Backend Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * *"

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python
        with:
          python-version-file: "backend/.python-version"
          working-directory: "backend"

      - name: Run Code Quality Checks
        uses: ./.github/actions/python-code-quality
        with:
          working-directory: "backend"

  test:
    name: Compose Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    env:
      SERVER_OPENAI_API_KEY: ${{ secrets.SERVER_OPENAI_API_KEY }}
      CLI_OPENAI_API_KEY: ${{ secrets.CLI_OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Docker Compose Tests
        uses: ./.github/actions/docker-compose-test
        with:
          working-directory: "backend"
