name: Backend Checks for Forked Repos

on:
  pull_request_target:
    branches: [main]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    environment: Contributors
    if: github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python
        with:
          python-version-file: "backend/.python-version"
          working-directory: "backend"

      - name: Run Code Quality Checks
        uses: ./.github/actions/python-code-quality
        with:
          working-directory: "backend"

  test:
    name: Compose Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: Contributors
    if: github.event.pull_request.head.repo.full_name != github.repository

    env:
      SERVER_OPENAI_API_KEY: ${{ secrets.SERVER_OPENAI_API_KEY }}
      CLI_OPENAI_API_KEY: ${{ secrets.CLI_OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Docker Compose Tests
        uses: ./.github/actions/docker-compose-test
        with:
          working-directory: "backend"
